spring:
  application:
    name: API-Gateway


server:
  port: 9092    
  
eureka:
 client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 instance:
   hostname: localhost
   leaseRenewalIntervalInSeconds: 15
   leaseExpirationDurationInSeconds: 30
  